<?php
    require_once('front/admin_bar.php');
    //require_once('front/wp_generator.php');
    //require_once('front/emoji.php');
    //require_once('front/pagination.php');
    //require_once('front/gf_msg_erreur.php');
    //require_once('front/gf_validation_telephone.php');
    //require_once('front/content_extrait.php');
    require_once('front/custom_login_css.php');
    require_once('front/custom_title_login.php');
    require_once('front/custom_url_login.php');
    //require_once('front/user_role.php');
    //require_once('front/var_dump.php');
    require_once('front/jquery.php');
    require_once('front/gf.php');
